version: '3'

services:
  db:
    image: postgres:10.1-alpine
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=${DB_PASSWORD}
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  server:
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
    command: "pipenv run server"
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: .docker/client/Dockerfile
    volumes:
      - ./client/src/:/usr/src/app/src
    command: "npm run serve"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - server

volumes:
  postgres_data: