# Generated by Django 2.2.2 on 2019-06-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='updated_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='updated_date',
            new_name='modified_date',
        ),
    ]
