# Generated by Django 2.2.2 on 2019-06-30 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20190630_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
