# Generated by Django 2.2.2 on 2019-06-30 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0004_auto_20190630_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('title', 'owner')},
        ),
    ]
