# Generated by Django 2.2.2 on 2019-06-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_auto_20190630_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_deleted',
        ),
    ]
