# Generated by Django 2.2.2 on 2019-07-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0006_remove_favorite_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['ranking', 'category']},
        ),
    ]
