# Generated by Django 2.2.2 on 2019-07-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0007_auto_20190701_0019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditlog',
        ),
    ]
