# Generated by Django 2.2.2 on 2019-07-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0009_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditlog',
        ),
    ]
