# Generated by Django 2.2.2 on 2019-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0011_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
