# Generated by Django 2.2.2 on 2019-07-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0012_favorite_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditlog',
        ),
    ]
