export const CLEAR_SERVER_ERROR = "CLEAR_SERVER_ERROR";
export const GET_AUDIT_LOGS_START = "GET_AUDIT_LOGS_START";
export const GET_AUDIT_LOGS_SUCCESS = "GET_AUDIT_LOGS_SUCCESS";
export const GET_AUDIT_LOGS_FAIL = "GET_AUDIT_LOGS_FAIL";
